"""
core/memory.py — Persistent storage manager for ContextKeeper 2.0

Manages the .context/ directory with atomic reads/writes and bi-directional
synchronisation with AGENTS.md (Bob's /init command format).
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from filelock import FileLock, Timeout

LOCK_TIMEOUT = 5  # seconds


def _context_dir() -> Path:
    """Resolve the context directory lazily so env-var overrides work in tests."""
    return Path(os.environ.get("CONTEXT_KEEPER_DIR", ".context"))


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _ensure_dirs() -> None:
    ctx = _context_dir()
    ctx.mkdir(parents=True, exist_ok=True)
    Path("reports").mkdir(parents=True, exist_ok=True)
    Path("bob_sessions").mkdir(parents=True, exist_ok=True)

    sessions_file = ctx / "sessions.json"
    if not sessions_file.exists():
        _write_json(sessions_file, {"tasks": [], "last_updated": _now()})


def _write_json(path: Path, data: dict[str, Any]) -> None:
    """Atomic write via temp-file replace."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(data, indent=2, default=str) + "\n", encoding="utf-8")
    tmp.replace(path)


def _read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def get_lock() -> FileLock:
    _ensure_dirs()
    return FileLock(str(_context_dir() / ".lock"), timeout=LOCK_TIMEOUT)


# ---------------------------------------------------------------------------
# Sessions
# ---------------------------------------------------------------------------

def load_sessions() -> dict[str, Any]:
    _ensure_dirs()
    return _read_json(_context_dir() / "sessions.json")


def upsert_task(
    task_id: str,
    summary: str,
    decisions: list[str],
    status: str,
) -> dict[str, Any]:
    """Insert or update a task record in sessions.json (idempotent)."""
    try:
        with get_lock():
            data = load_sessions()
            tasks: list[dict[str, Any]] = data.get("tasks", [])
            existing = next((t for t in tasks if t["task_id"] == task_id), None)
            entry: dict[str, Any] = {
                "task_id": task_id,
                "summary": summary,
                "decisions": decisions,
                "status": status,
                "updated_at": _now(),
            }
            if existing:
                existing.update(entry)
            else:
                entry["created_at"] = _now()
                tasks.append(entry)
            data["tasks"] = tasks
            data["last_updated"] = _now()
            _write_json(_context_dir() / "sessions.json", data)
            return entry
    except Timeout:
        raise RuntimeError("Storage lock timeout — another session is writing. Retry.")


# ---------------------------------------------------------------------------
# AGENTS.md synchronisation
# ---------------------------------------------------------------------------

def _render_agents_md(tasks: list[dict[str, Any]]) -> str:
    """Render all tasks as an AGENTS.md compatible markdown document."""
    lines = [
        "# AGENTS.md — ContextKeeper 2.0 Session Log",
        "",
        "> Auto-generated by ContextKeeper 2.0. Compatible with Bob's `/init` command.",
        "",
        "## Active Tasks",
        "",
    ]
    active = [t for t in tasks if t.get("status") != "done"]
    done = [t for t in tasks if t.get("status") == "done"]

    for t in active:
        lines.append(f"### [{t['task_id']}] {t['summary']}")
        lines.append(f"- **Status:** `{t.get('status', 'unknown')}`")
        lines.append(f"- **Updated:** {t.get('updated_at', '?')}")
        if t.get("decisions"):
            lines.append("- **Decisions:**")
            for d in t["decisions"]:
                lines.append(f"  - {d}")
        lines.append("")

    if done:
        lines += ["## Completed Tasks", ""]
        for t in done:
            lines.append(f"- ✅ **[{t['task_id']}]** {t['summary']} _(done {t.get('updated_at', '?')})_")
        lines.append("")

    return "\n".join(lines)


def sync_agents_md() -> None:
    """Write AGENTS.md from current sessions.json state (best-effort)."""
    try:
        data = load_sessions()
        tasks = data.get("tasks", [])
        Path("AGENTS.md").write_text(_render_agents_md(tasks), encoding="utf-8")
    except Exception:
        pass  # never crash a tool call over AGENTS.md sync


# ---------------------------------------------------------------------------
# Constraints helpers
# ---------------------------------------------------------------------------

def load_constraints() -> dict[str, Any]:
    _ensure_dirs()
    return _read_json(_context_dir() / "constraints.json")


def load_deprecated_rules() -> dict[str, Any]:
    _ensure_dirs()
    return _read_json(_context_dir() / "deprecated_rules.json")
